-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE public.zajezdnie;
CREATE TABLE IF NOT EXISTS public.zajezdnie
(
    id_zajezdni bigint,
    nazwa_zajezdni text,
    adres_zajezdni text,
    typ_zajezdni text,
    miasto text,
    dzielnica text,
    PRIMARY KEY (id_zajezdni)
);

CREATE TABLE IF NOT EXISTS public.typy_zajezdni
(
    typ_zajezdni bigint,
    nazwa_typu text,
    PRIMARY KEY (typ_zajezdni)
);

CREATE TABLE IF NOT EXISTS public.pracownicy
(
    id_pracownika bigint,
    imie text,
    nazwisko text,
    pesel bigint,
    wiek bigint,
    nr_tel bigint,
    id_stanowiska bigint,
    id_zajezdni bigint,
    PRIMARY KEY (id_pracownika)
);

CREATE TABLE IF NOT EXISTS public.stanowiska
(
    id_stanowiska bigint,
    stanowisko text,
    PRIMARY KEY (id_stanowiska, stanowisko)
);

CREATE TABLE IF NOT EXISTS public.pojazdy
(
    id_pojazdu bigint,
    id_marki_modelu bigint,
    rok_prod date,
    "VIN" text,
    PRIMARY KEY (id_pojazdu, id_marki_modelu)
);

CREATE TABLE IF NOT EXISTS public.marki_modele
(
    id_marki_modelu bigint,
    id_marki bigint,
    id_modelu bigint,
    id_grupy bigint,
    PRIMARY KEY (id_marki_modelu, id_marki, id_modelu, id_grupy)
);

CREATE TABLE IF NOT EXISTS public.marki
(
    id_marki bigint,
    nazwa_marki text,
    PRIMARY KEY (id_marki, nazwa_marki)
);

CREATE TABLE IF NOT EXISTS public.modele
(
    id_modelu bigint,
    nazwa_modelu text,
    PRIMARY KEY (id_modelu)
);

CREATE TABLE IF NOT EXISTS public.grupy
(
    id_grupy bigint,
    grupa text,
    PRIMARY KEY (id_grupy)
);

ALTER TABLE IF EXISTS public.zajezdnie
    ADD FOREIGN KEY (typ_zajezdni)
    REFERENCES public.typy_zajezdni (typ_zajezdni) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.zajezdnie
    ADD FOREIGN KEY (typ_zajezdni)
    REFERENCES public.pracownicy (id_zajezdni) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pracownicy
    ADD FOREIGN KEY (id_stanowiska)
    REFERENCES public.stanowiska (id_stanowiska) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pojazdy
    ADD FOREIGN KEY (id_marki_modelu)
    REFERENCES public.marki_modele (id_marki_modelu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.marki_modele
    ADD FOREIGN KEY (id_marki)
    REFERENCES public.marki (id_marki) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.marki_modele
    ADD FOREIGN KEY (id_modelu)
    REFERENCES public.modele (id_modelu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.marki_modele
    ADD FOREIGN KEY (id_grupy)
    REFERENCES public.grupy (id_grupy) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;





insert into zajezdnie (id_zajezdni, nazwa_zajezdni, adres_zajezdni, typ_zajezdni, miasto, dzielnica)
VALUES(1,'OKM','Warszawska 16a',null,'Ostroleka','Kochlowice');

SELECT * FROM public.zajezdnie;